### ISSUE TITLE
YOLO

### ISSUE THREAD

**Issue by khaitha** [kamkyu94/AdapTrack#2]
Hello, How can I use this model with YOLO weight. for tracking in a video?
안녕하세요, YOLO 무게로 이 모델을 사용하려면 어떻게 해야 합니까? 비디오에서 추적하기 위해?

**Comment by kamkyu94** [comment]
Hello.

You can refer the guidelines below. And feel free to revise the codes as you needed.

  - https://github.com/kamkyu94/AdapTrack/blob/main/README.md
  - https://github.com/kamkyu94/AdapTrack/blob/main/1.%20YOLOX/README.md
  - https://github.com/kamkyu94/AdapTrack/blob/main/2.%20FastReID/README.md
  - https://github.com/kamkyu94/AdapTrack/blob/main/3.%20AdapTrack/README.md

Thank you for your attention.

Sincerely Kyujin Shim
